//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieV04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingCnf
    {
        public string UserName { get; set; }
        public string Movie { get; set; }
        public int Id { get; set; }
        public double Price { get; set; }
    }
}
