//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieV04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MovieCategory { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string Trailer { get; set; }
    }
}
