//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieV04.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineMovieTicketEntities : DbContext
    {
        public OnlineMovieTicketEntities()
            : base("name=OnlineMovieTicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingCnf> BookingCnfs { get; set; }
        public virtual DbSet<Dashbord> Dashbords { get; set; }
        public virtual DbSet<MovieDetail> MovieDetails { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
